-- DROP DATABASE IF EXISTS project2_db;
--
-- CREATE DATABASE project2_db;
--
-- USE project2_db;
--
-- CREATE TABLE restrooms (
--   id AUTO_INCREMENT NOT NULL,
--   location_name VARCHAR(255) NOT NULL,
--   street VARCHAR(255) NOT NULL,
--   city VARCHAR(255) NOT NULL,
--   comments VARCHAR(255) NOT NULL,
--   PRIMARY KEY(id)
-- );
--
-- CREATE TABLE gas_stations (
--   id AUTO_INCREMENT NOT NULL,
--   location_name VARCHAR(255) NOT NULL,
--   street VARCHAR(255) NOT NULL,
--   city VARCHAR(255) NOT NULL,
--   has_restroom BOOLEAN DEFAULT FALSE,
--   comments VARCHAR(255) NOT NULL,
--   PRIMARY KEY(id)
-- );
--
-- CREATE TABLE coffee_shops (
--   id AUTO_INCREMENT NOT NULL,
--   location_name VARCHAR(255) NOT NULL,
--   street VARCHAR(255) NOT NULL,
--   city VARCHAR(255) NOT NULL,
--   has_restroom BOOLEAN DEFAULT FALSE,
--   comments VARCHAR(255) NOT NULL,
--   PRIMARY KEY(id)
--   );
--
-- -- // Only need one table for restrooms that fall into different categories
-- -- attributes: id (auto-increment not null), lat, lng, name (can be null), hours - can be null, category (radio - gas station, restaurant/cafe, other),

DROP DATABASE IF EXISTS 'gotta_go_db';
CREATE DATABASE 'gotta_go_db';
